### ISSUE TITLE
App Layout Suggestions to reduce Scrolling

### ISSUE THREAD

**Issue by jarumihooi** [clamsproject/aapb-annenv-creditparsing#7]
### Because

Collecting suggestions to improve the annotation app layout. 

Goal: Reduce scrolling during common workflows. Streamline tool clicks. 
Note: Suggested to have the "4 frame buttons" TWICE. Once on top once on bottom.

The Common Workflows and their needs: 
1. Fast Skip - Having new "frame" and "button for skip or duplicate" at top would be nice. 
2. Simple Pt1 - Annotating a simple frame with maybe only one k-v pair. Need to see "frames", "add current annotation", and 3 rows or so of the "add buttons"
3. Simple Pt2 - When frame has a lot of values for 1 key. We can scroll if the "add buttons" don't all fit on screen. 
4. Review Complex - Annotating multiple k-v pairs. We start with similar needs in Workflow2. However later into the k-v pairs we may need to see only the button to "add new pair", most of the "add buttons" and the "frames". 
At the end of this workflow, annotator will want to see the "current staged annotations" AND the "frames" again before clicking the "4 buttons". Therefore, its suggested that the "4 buttons" appear twice, have a second appearance of the "frames", and scrolling to the bottom can be used to view these 3 needs all at once. 

Finally, the bottom seems to be a good place to have "delete annotation", and "frame navigation/progress". I don't think its required to see progress at the top of the app for every frame. 

Please see two suggestions for app layout: 
![IMG_2940](https://github.com/clamsproject/aapb-annenv-creditparsing/assets/47136910/ec7b7356-0b12-45ea-b208-8a5197ae4682)
Note: place the "delete annotation" and "frame navigation" at the bottom of this version as well.
[App Layout (1).pdf](https://github.com/clamsproject/aapb-annenv-creditparsing/files/12614369/App.Layout.1.pdf)

### Done when

- [ ] App is changed according to what is possible, and reduces scrolling and extraneous click to be reasonably not hinder use. 
- [ ] Annotation Team agrees on the above (without being too picky).

**Comment by keighrim** [comment]
A few more feature requests from yesterday's meeting. 

- [ ] add links to AAPB online reading room page
- [ ] add "save&proceed" button on the top as well (for quick move-on for images with a single k-v)
